### PR TITLE
Add iTerm as terminal option for macOS

### PR DESCRIPTION
**Pull request by DrJume**
Added AppleScript integration for iTerm using `appscript` which is already used.

### CODE REVIEW

**Comment by Skazza94** [comment]
Hi @DrJume,
sorry for the delay and thanks for the PR.

I tested the changes on a macOS Catalina (10.15.4) and `iTerm` seems to not be installed. Instead, `Terminal` is present.

Since I'm not a Mac-user, could you please explain me what `iTerm` is? Is it related to old macOS versions?

Thanks.

**Comment by DrJume** [comment]
`iTerm` is an open source alternative terminal application with more features than the system provided `Terminal.app`.

You can get `iTerm` here: https://iterm2.com/

**Comment by Skazza94** [comment]
Hi @DrJume,
the PR seems good, I'll merge it into `minor_improvements` which is the branch for the next release (3.1.0)

Thanks for contributing!
Mariano.

**Comment by DrJume** [comment]
You're welcome.
Thank you for maintaining Kathara!

**Pull request merged**
